{% set data = load_setup_py_data() %}

package:
  name: argdash
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/argdash.git

build:
  number: 0
  script: python -m pip install . -vv
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:  # your library dependencies
    - python
    - jupyterlab
    - dash
    - dash-bootstrap-components
    - pandas
    - networkx
    - jupyter-dash
    - plotly
    
channels:  # channels for your library dependencies
  - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build=24 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  
test:
  imports:
    - argdash

about:
  home: https://github.com/munch-group/argdash.git
  license: MIT
  dev_url: https://github.com/munch-group/argdash.git
  doc_url: https://munch-group.org/argdash
